[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
runner = "elf2uf2-rs -d"  # writes built files to RP2040 flash on run
# runner = "probe-run --chip RP2040"

# rustflags = [
#   "-C", "link-arg=-Tlink.x",
#   "-C", "link-arg=--nmagic",
#   # Flag required for defmt, when using probe-run
#   "-C", "link-arg=-Tdefmt.x",
# ]

[env]
DEFMT_LOG = "debug"